#!/system/bin/sh

# Redirect output to logcat
BB="busybox";

# Swapoff all first
if swap_files=$($BB grep "/" /proc/swaps | $BB awk '{print $1}'); then
	for i in $swap_files; do
		$BB swapoff $i
	done
fi

# Set page-cluster to lowest to maximize performance
$BB echo 0 > /proc/sys/vm/page-cluster;

# How many CPU cores do we have?
cpu_sysfs_paths=$($BB ls /sys/devices/system/cpu | $BB grep cpu | $BB wc -l)
num_cpu=$($BB expr ${cpu_sysfs_paths} - 2) # Except cpufreq and cpuidle sysfs path

# Remove all zRAMs first
for i in $($BB seq ${num_cpu}); do
	num=$((i - 1));
	$BB echo ${num} > /sys/class/zram-control/hot_remove;
done;

# Calculate memory to use for zram (1/2 of ram)
totalmem=$($BB free | grep -e "^Mem:" | $BB sed -e 's/^Mem: *//' -e 's/  *.*//')
mem=$(((totalmem / 2 / ${num_cpu}) * 1024))

# Now let's start
for i in $($BB seq ${num_cpu}); do
	num=$((i - 1));

	$BB cat /sys/class/zram-control/hot_add;
	$BB echo ${mem} > /sys/block/zram${num}/disksize;
	$BB mkswap /dev/block/zram${num};
	swapon -p 05 /dev/block/zram${num};
done;

# Set maximum swappiness
$BB echo 100 > /proc/sys/vm/swappiness;
